### ISSUE TITLE
including or excluding accounts?

### ISSUE THREAD

**Issue by tommens** [mehdigolzadeh/BoDeGa#10]
By default, when running bodega on a GitHub repository, all accounts in that repository are *included* in the analysis. It is also possible to run bodega on a set of accounts provided as input. However, this is very impractical if the set of accounts is very big. What if you want to run bodega on all accounts in a repository, *except* for a given number of known accounts. In that case, it would be much more practical to specify which accounts need to be *excluded*, instead of mentioning all of those that should be *included*. What do you think?

**Comment by AlexandreDecan** [comment]
I +1 this suggestion. Having a `--exclude` option would be interesting and easy to implement.

**Comment by mehdigolzadeh** [comment]
Good Idea. I will git it a try. `--exclude` to exclude a list of accounts.

**Comment by mehdigolzadeh** [comment]
This feature added by pull request #11
