### ISSUE TITLE
Rename BoDeGa into BoDeGHa

### ISSUE THREAD

**Issue by tommens** [mehdigolzadeh/BoDeGa#13]
The name Bodega is already used by many other repositories.
Moreover the name "BoDeGHa" is better, since it is an acronym for "Bot Detection in GitHub accounts".
Can you therefore rename this git repository, the name of the tool as well, and also all references to this tool in all our publications referring to it? Know is the time to do so, before we have an official publication of the tool...

**Comment by AlexandreDecan** [comment]
Given the acronym, shouldn't "a" be in uppercase?

**Comment by mehdigolzadeh** [comment]
Updated
