### ISSUE TITLE
update readme file

### ISSUE THREAD

**Issue by tommens** [mehdigolzadeh/BoDeGa#16]
@mehdigolzadeh can you update the readme file to:

- specify the (open source) licence we have used
- put a link to the, now accepted, JSS publication accompanying the tool
- improve the readme file documentation explaining the use of the tool and the limitations of the parameters (e.g. the fact that we have not tested the classification model certain values outside predefined parameter boundaries; as a result, the tool may be less precise for those cases)
- make it sufficiently clear to the user of the tool that the classification model DOES misclassify bots and humans from time to time; this is not a bug, it is an inherent part of the classification model
- perhaps also inform the user that, in some cases (such as the use of templates in comments), the tool may give rise to more misclassifications than usual

**Comment by mehdigolzadeh** [comment]
We have updated the readme file,

Thanks
