### ISSUE TITLE
University-of-Mons

### ISSUE THREAD

**Issue by tommens** [mehdigolzadeh/BoDeGa#6]
Given that BoDeGa has been created as a research project that was carried out as part of, and financed on research funds received by, the University of Mons, I think it makes sense to move the github repo to the github.com/University-of-Mons domain. Can this be done without losing any historic information, such as all commits, issues and pull requests? (I guess so...)
If we go for this solution, we should do it soon, before the tool is getting traction. What are your thoughts om that?

**Comment by mehdigolzadeh** [comment]
Isn't it enough to add University of Mons as my organization?

**Comment by AlexandreDecan** [comment]
It's definitely doable to transfer the ownership of the repository to an organization without losing any information. 
However, I suggest to wait the acceptance of the paper (and probably bodega 1.0.0) to do so. Currently, the tool is not enough mature to be considered as stable, and to be *officially* distributed as-is through Github.

**Comment by tommens** [comment]
Fine by me.
